config/routes.rb
Rails.application.routes.draw do  
 
  
  
  
  ActiveAdmin.routes(self)
  get 'requests/index'
  get 'requests/show'
  get 'requests/update'
  get 'requests/destroy'
  get 'requests/edit'
  get 'requests/create'
  get 'requests/new'
  root 'pages#home'
  get 'pages/home'
  get 'pages/home_landlord'
  get 'properties/index'
  get 'properties/new'
  get 'properties/create'
  get 'properties/update'
  get 'properties/show'
  get 'properties/edit'
  get 'properties/destroy'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :properties
      devise_for :users, 
                  :controllers => {registrations: "api/v1/registrations", sessions: "api/v1/sessions"},
                  path_names: { sign_in: :login }
      resources :users, only: [:show]  
      resources :purchases, only: [:index]
      resources :points, only: [:index]          
    end
  end

  devise_for :users,
             :controllers => {registrations: 'registrations'},
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'}
             
  resources :landlords do
    member do
      delete :delete_image_attachment
    end  
  end  
  resources :tenants do
    member do
      delete :delete_image_attachment
    end  
  end  
  resources :properties
  resources :requests do
    member do
      get 'responses'
      get 'response_property'
      patch :activate
      put :activate
      get 'congratulations'
    end  
  end  
  resources :properties do
    member do
      get 'all_requests'
      get 'show_request'
      delete :delete_image_attachment
      patch :activate
      put :activate
      get 'congratulations'
    end  
  end

  resources :purchases
  resources :points

  resources :properties do
    resources :requests do        
      resources :purchases        
    end  
  end

  resources :properties do
    resources :requests do 
      resources :points         
    end  
  end

  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"

 

  get '/notifications' => 'notifications#index'

  get '/payment_method' => "landlords#payment"
  post '/add_card' => "landlords#add_card"

  resources :conversations, only: [:index, :create]  do
    resources :messages, only: [:index, :create]
  end

  require 'sidekiq/web'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'
end

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/property.rb
class Property < ApplicationRecord
  validates :property_name, presence: true
  validates :price, presence: true
  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :accommodate, presence: true
  validates :address, presence: true
  validates :minimum_lease, presence: true
  validates :summary, presence: true

  belongs_to :user
  has_many :purchases
  has_many :points
  has_many :connections
  has_many_attached :images

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/controllers/api/v1/properties_controller.rb
class Api::V1::PropertiesController < ApplicationController
	
	acts_as_token_authentication_handler_for User, fallback: :none
	protect_from_forgery with: :null_session
	respond_to :json

	def index
		@properties = Property.all
		@newproperties = @properties.map { |property| property_json(property) }
		respond_with @newproperties
	end

	def show
		@property = Property.find(params[:id])
		@newproperty = property_json(@property)
		respond_with @newproperty
	end

	private

	def property_json(property)
    	@requests = helpers.getenquires(property)
    	property.as_json.merge(images: property.images.map { |image| url_for(image) }, requests: @requests)
  	end
end



app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, except: [:index, :new, :create, :all_requests, :show_request, :delete_image_attachment]
  before_action :authenticate_user!, except: [:new, :create] 


  def index
    @properties = current_user.properties
  end

  def new
    if user_signed_in?
      @property = current_user.properties.build
    else
      @property = Property.new
    end

  end

  def create
    if current_user.nil?
      session[:property] = params
     # Redirect the user to register/login
      redirect_to new_user_registration_path  
    else
      @property = current_user.properties.build(property_params)
      if @property.save
        PropertyMailer.new_property_email(@property).deliver_later
        PropertyMailer.new_property_admin_email(@property).deliver_later
        redirect_to congratulations_property_path(@property), notice: "Saved..."
      else
        flash[:alert] = "Something went wrong..."
        render :new
      end
    end    
  end

  def activate
    if @property.active?
      @property.update_attribute(:active, false)
    else
      @property.update_attribute(:active, true)
    end
    redirect_to request.referer
  end

  def update
    authorize! :update, @property
    if @property.update(property_params)
      PropertyMailer.update_property_email(@property).deliver_later
      PropertyMailer.update_property_admin_email(@property).deliver_later
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Something went wrong..."
    end
    redirect_back(fallback_location: request.referer)
  end

  def show
    @requests = helpers.getenquires(@property)
    authorize! :read, @property   
  end
  
  def all_requests
    @property = Property.find(params[:id])
    @requests = helpers.getenquires(@property)
  end

  def show_request
    session["property_id"] = params[:id]
    @property = Property.find(params[:id])
    @request = Request.find(params[:format])
    @purchase = @request.purchases.build
    @point = @request.points.build
  end

  def edit
    authorize! :edit, @property
  end

  def destroy
    authorize! :destroy, @property
      @property = Property.find(params[:id])
      @property.destroy

      redirect_to properties_path
  end

  def delete_image_attachment
    @image = ActiveStorage::Attachment.find(params[:id])
    @image.purge
    redirect_back(fallback_location: request.referer, notice: "Saved...")
  end

  def congratulations
    
  end




  private  


  def property_params
      params.require(:property).permit(:property_name, :price, :home_type, :room_type, :accommodate, :bed_room, :bath_room, :is_air, :is_parking, :is_washer, :is_balcony, :is_fireplace, :is_internet, :is_gym, :is_pool, :is_dogs, :is_cats, :is_wheelchair, :is_smoking, :city, :address, :minimum_lease, :summary, :active, images: [])
  end

  def set_property
    @property = Property.find(params[:id])
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_map.html.erb
<div id="map" style="width: 100%; height: 400px"></div>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLEMAP_API'] %>"></script>
<script>
function initialize() {
    var location = {lat: <%= @property.latitude %>, lng: <%= @property.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
        center: location,
        zoom: 14
        });

    var image =  {
       	url: "<%= image_path('location.svg') %>"
        };

    var marker = new google.maps.Marker({
        position: location,
        map: map,
        icon: image
        });
           
    }

google.maps.event.addDomListener(window, 'load', initialize);
</script>

app/views/properties/_photos_list.erb

  <% @property.images.each do |image| %>
    <span><%= image_tag image %> <a href="<%= delete_image_attachment_property_path(image.id) %>" class="remove-image-btn" data-method="delete"><%= image_tag 'close.png' %></a></span>
    
  <% end %>


app/views/properties/_property.html.erb
<div class="col-md-4">
	<div class="property-slide-bx">
	   	<div class="property-slider-01 owl-carousel owl-theme">
	        <% property.images.each do |image| %>
	           	<div class="item">
	               	<div class="propert-image-box">
	               		<%= image_tag image %>
	               	</div>
	            </div>
	        <% end %>	                                
	    </div>
	    <div class="property-detail-bx" style="display: flex;">
	       	<div class="pro-dtl-sec">
	           	<%= link_to property do %>
	           		<h5><%= property.property_name %></h5>
	         	<% end %>
	            <span class="city-name"><%= property.address %></span>
	        </div>
	        <div class="pro-bed-bx">
	           	<ul>
	               	<li>
	               		<span class="bed-icon"><%= image_tag("bed-icon.png", :alt => "") %></span> <span class="pro-count"><%= property.bed_room %></span>
	               	</li>
	                <li>
	                	<span class="bathtub-icon"><%= image_tag("bathtub-icon.png", :alt => "") %></span> <span class="pro-count"><%= property.bath_room %></span>
	                </li>
	            </ul>
	        </div>
	    </div>
	    <div class="pro-btn-sec">
	       	<% @requests = getenquires(property) %>
	        <a href="<%= all_requests_property_url(property) %>" class="light-blue-btn">Enquiries <span>(<%=@requests.length %>)</span></a>
	        <a href="<%= edit_property_path(property) %>" class="light-red-btn" >Edit</a> 	        
	    </div>
	</div>
</div>

app/views/properties/_sidebar.html.erb
<div class="l-sidebar aside-1">
  <div class="landloard-profile-inbox">
    <%= showavatar(current_user) %>
  </div>
  <ul class="l-menu">
              
    <li class="<%= cp(properties_path) %>"> <a href="<%= properties_path %>"><span class="l-p-icon"><%= image_tag 'home-icon.png' %></span>Properties</a></li>
    <% if profile(current_user) %>
      <li class="<%= cp(landlord_path(profile(current_user))) %>"> 
        <a href="<%= landlord_path(profile(current_user)) %>"><span class="l-p-icon">                
          <%= image_tag 'user.png' %>                
        </span>Profile</a>
      </li>
    <% else %>
      <li class="<%= cp(create_profile(current_user)) %>"> 
        <a href="<%= create_profile(current_user) %>"><span class="l-p-icon">                
          <%= image_tag 'user.png' %>                
        </span>Profile</a>
      </li>
    <% end %>
    <li class="<%= cp(conversations_path) %>"><a href="<%= conversations_path %>"><span class="l-p-icon"><%= image_tag "mail-icon-grey.png" %></span>Messages</a></li>
    <li class="<%= cp(edit_user_registration_path) %>"><a href="<%= edit_user_registration_path %>"><span class="l-p-icon"><%= image_tag 'padlock-grey.png' %></span>Security</a></li>
    <% if current_user.stripe_id  %>
      <li class="<%= cp(payment_method_path) %>"><a href="<%= payment_method_path %>"><span class="l-p-icon"><%= image_tag 'credit-card.png' %></span>Update Credit Card</a></li>
    <% else %>
      <li class="<%= cp(payment_method_path) %>"><a href="<%= payment_method_path %>"><span class="l-p-icon"><%= image_tag 'credit-card.png' %></span> Add Credit Card</a></li>
    <% end %>
              
              
    <li class="logout-link">
      <%= link_to destroy_user_session_path, method: :delete do %>
        <span class="l-p-icon"><%= image_tag 'logout.png' %></span>Log out
      <% end %>
    </li>
  </ul>
  <div class="l-side-btn-sec"> <a href="#" class="light-blue-btn">+ New Property</a> </div>
</div>

app/views/properties/all_requests.html.erb
<section class="landloard-content">
  		<div class="container">
        	<div class="row">
        	<div class="col-md-3">
            	<%= render 'sidebar' %>
            </div>
            
            <div class="col-md-9">
            	<div class="landloard-rt-sec  new-rt-landloard-sec">
                	<div class="row">
                	<div class="col-md-12">
                    	<div class="back-to-req-sec">
            	<a href="<%= properties_url %>" class="back-to-request">
                	<span class="back-arrow"></span> <span>Back to properties</span>
                </a>	
            </div>
            <hr>
                    </div>
                </div>
                
                	<div class="row">
                    	<div class="col-md-12">
                        	<h3 class="property-top-title">You have <span><%= @requests.count %> <%= pluralize_without_count(@requests.count, 'request') %></span> for your property “An Apartment”</h3>
                        </div>
                    </div>
                
                	<div class="row">
                    	
						<% @requests.each do |requesto| %>
                    	<div class="col-md-4">
                        	<div class="apartment-pro-bx list-common">
                            	<div class="apartment-header">
                                	<h5><%= requesto.home_type %></h5>
                                    <div class="row">
                                    	<div class="col-sm-6">
                                        	<span class="location-name">
                                                <%= requesto.city %> 
                                                <% @districts = requesto.address.gsub(/(\[\"|\"\])/, '').split('", "') %>                      
                                                (<%= @districts.map{|district| district}.join(", ") %>)</span>
                                        </div>
                                        <div class="col-md-6 text-right">
                                        	<span class="property-price">
                                            	$<%= requesto.min_budget %>-<%= requesto.max_budget %>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="apartment-dtl-list">
                                	<ul class="pro-dtl-list">
					                    <li><span class="f-icon"><%= image_tag 'calendar.png' %></span> <span><%= requesto.arrival_date %> - <%= requesto.duration %></span> Months</li>
					                    <li><span class="f-icon"><%= image_tag 'bed-grey-icon-1.png' %></span> <span><%= requesto.bed_room %></span> <%= pluralize_without_count(requesto.bed_room, 'bedroom') %></li>
					                    <li><span class="f-icon"><%= image_tag 'bathtub-grey-icon-1.png' %></span> <span><%= requesto.bath_room %></span> <%= pluralize_without_count(requesto.bath_room, 'bathroom') %></li>
					                  </ul>
                  
                  					<a href="<%= show_request_property_path(@property, requesto) %>" class="light-blue-btn">Show more</a>
                                </div>
                            </div>
                        </div>
                        <% end %>
                    </div>
                </div>
            </div>
            </div>
        </div>	
  </section>
  <!-- landloard-profile end here -->

app/views/properties/congratulations.html.erb
<section class="landloard-step-sec">
  <div class="container">
    <div class="row landloar-cong-sec">

      <div class="col-sm-12">
        <div class="row">

          <div class="col-md-8">
            <div class="step-header">
              <span class="step-name">Congratulations!</span>

            </div>
            <h2 class="heading-level-01">Your Property Has Been Added!</h2>

            <p class="next-steps">Your next steps:</p>

            <div class="row">

              <div class="col-md-12">
                <ul class="next-steps-list">
                  <li class="active">
                    <a href="#">
                      <span class="step-icon-bx">
                        <%= image_tag 'checked-symbol.png' %>
                        <%= image_tag 'checked-symbol-active.png' %>
                      </span>
                      <span class="step-text">
                        Your property has added!
                      </span>
                    </a>
                  </li>
                  <li>
                   <a href="#">
                    <span class="step-icon-bx">
                      <%= image_tag 'yellow-message.png' %>
                      <%= image_tag 'yellow-message-active.jpg' %>
                    </span>
                    <span class="step-text">
                      Wait for tenants requests
                    </span>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <span class="step-icon-bx">
                      <%= image_tag 'yellow-money.png' %>
                      <%= image_tag 'yellow-money-active.jpg' %>
                    </span>
                    <span class="step-text">
                      Start earning with your property!
                    </span>
                  </a>
                </li>
              </ul>
              <div class="step-btn-pagination">
               <div class="up-broken-line-arrow">
                 <ul>
                  <li>
                    <%= image_tag 'up-broken-line-arrow1.png' %></li>
                    <li>
                      <%= image_tag 'up-broken-line-arrow2.png' %></li>
                      <li>
                        <%= image_tag 'up-broken-line-arrow3.png' %></li>
                      </ul>
                    </div>
                    <% if profile(current_user) %>
                    <a href="<%= landlord_path(profile(current_user)) %>" class="blue-outline-btn arrow-none-btn">View your profile</a>
                    <% else %>
                    <!--<a href="<%= create_profile(current_user) %>" class="blue-outline-btn arrow-none-btn">Complete your profile</a>-->
                    <% end %>
                    <a href="<%= properties_path %>" class="primary-btn goto-reques-btn">Checkout Dashboard</a>
                  </div>
                </div>



              </div>
            </div>
            <div class="col-md-4">
             <div class="step-rt-img-sec">
               <%= image_tag 'step-7.jpg' %>
             </div>
           </div>
         </div>


       </div>
     </div>

   </div>
 </section>
  <!-- landloard-profile end here -->

app/views/properties/create.html.erb
<h1>Properties#create</h1>
<p>Find me in app/views/properties/create.html.erb</p>

app/views/properties/destroy.html.erb
<h1>Properties#destroy</h1>
<p>Find me in app/views/properties/destroy.html.erb</p>

app/views/properties/index.html.erb
<section class="landloard-content">
  	<div class="container">
       	<div class="row">
        	<div class="col-md-3">
            	<!-- Sidebar here -->
          		<%= render 'sidebar' %>
            </div>
            
            <div class="col-md-9">
            	<div class="landloard-rt-sec">
                	<div class="row">
                    	<%= render @properties %>
                    </div>
                </div>
            </div>
        </div>
    </div>	
</section>
<!-- landloard-profile end here -->

app/views/properties/show.html.erb
	<section class="landloard-content">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
         <!-- Sidebar here -->
          <%= render 'sidebar' %>
        </div>
        <div class="col-md-9">
        	
          <div class="landloard-rt-sec">
          		<div class="row">
                	<div class="col-md-12">
                    	<div class="back-to-req-sec">
            	<a href="<%= properties_path %>" class="back-to-request">
                	<span class="back-arrow"></span> <span>Back to Properties</span>
                </a>	
            </div>
                    </div>
                </div>
            <div class="row">
            
            <div class="col-md-12">
            	<div class="pro-l-open-property">
                <div class="row">
                 	<div class="col-md-6">
                    <div id="sync1" class="owl-carousel">
                      <% @property.images.each do |image| %>
            				    <div class="item">
            				      <%= image_tag image %>
            				    </div>
            				  <% end %>                 
                    </div>
                    <div id="sync2" class="owl-carousel">
                      <% @property.images.each do |image| %>
            				    <div class="item">
            				      <%= image_tag image %>
            				    </div>
            				  <% end %>                  
                    </div>
                  </div>

              	 <div class="col-md-6">              	 	
              	 	<div class="row pro-l-head">
                    <div class="col-md-8">
                      <h4><%= @property.property_name %></h4>
                      <span class="location-address"><%= @property.city %>, <%= @property.address %></span>
                    </div>
                    <div class="col-md-4 property-price">
                      <h4>$<%= @property.price %></h4>
                    </div>
                  </div>
                    
                    <ul class="l-p-dtl-list">
                    	<li><span class="f-icon"><%= image_tag("real-estate.png", :alt => "") %></span> <%= @property.home_type %></li>
                        <li><span class="f-icon"><%= image_tag("shared.png", :alt => "") %></span> <%= @property.room_type %></li>
                    	<li><span class="f-icon"><%= image_tag("bed-grey-icon-1.png", :alt => "") %></span><span class="f-count"><%= @property.bed_room %></span> Bedrooms</li>
                        <li><span class="f-icon"><%= image_tag("accommodate.png", :alt => "") %></span><span class="f-count"><%= @property.accommodate %></span> Accommodate </li>
                        <li><span class="f-icon"><%= image_tag("bathtub-grey-icon-1.png", :alt => "") %></span><span class="f-count"><%= @property.bath_room %></span> Bathrooms</li>
                        <li><span class="f-icon"><%= image_tag("calendar.png", :alt => "") %></span><span class="f-count"><%= @property.minimum_lease %></span></li>
                    </ul>              	 	                   
                    
                    
                    <div class="row">
                    	<div class="col-md-12">
                        <div class="pro-btn-sec">
                          <a href="<%= all_requests_property_path %>" class="light-blue-btn">Enquiries <span>(<%=@requests.length %>)</span></a>
                          <% if @property.active? %>
                            <%= link_to 'Deactivate', activate_property_path(@property),       method: :put, data: { confirm: 'This property would be deactivated' }, class: "light-red-btn" %>
                          <% else %>
                            <%= link_to 'Activate', activate_property_path(@property), method: :put, data: { confirm: 'This property would be activated' }, class: "light-red-btn" %>
                          <% end %>
                          <a href="<%= edit_property_path %>" class="light-red-btn" style="width: 100%; margin-top: 5px;">Edit</a>                         	
                          
                        </div>
                      </div>
                    </div>
                 </div>

                 <div class="col-md-12">
                 	<div class="p-l-desc">
                 	<p><%= @property.summary %></p>
                    </div>
                 </div>
              </div>
                            
              <div class="row">
              	<div class="col-md-12 mt-4 mb-4 pro-feature-sec">
                	<h5>Features</h5>
                	<ul class="features-list">
                    	<% if @property.is_air %>
                    		<li>                       	
	                        	<div class="list-block"><div><span class="feature-img"><%= image_tag("air-conditioner.png", :alt => "") %></span><span>Airconditioning </span></div></div>
	                        </li>                    		
                    	<% end %>
                    	<% if @property.is_parking %>
                    		<li>                       	
	                        	<div class="list-block"><div><span class="feature-img"><%= image_tag("parking.png", :alt => "") %></span><span>Parking/
								Garage </span></div></div>
	                        </li>                    		
                    	<% end %>

                    	<% if @property.is_washer %>
                    		<li>                       	
	                        	<div class="list-block"><div><span class="feature-img"><%= image_tag("washing-machine.png", :alt => "") %></span><span>Washing machine </span></div></div>
	                        </li>
                    	<% end %>

                    	<% if @property.is_balcony %>
                    		<li>                       	
	                        	<div class="list-block"><div><span class="feature-img"><%= image_tag("balcony.png", :alt => "") %></span><span>Balcony</span></div></div>
	                        </li>
                    	<% end %>

                    	<% if @property.is_fireplace %>
                    		<li>                       	
	                        	<div class="list-block"><div><span class="feature-img"><%= image_tag("fireplace.png", :alt => "") %></span><span>Fireplace</span></div></div>
	                        </li>
                    	<% end %>

                    	<% if @property.is_internet %>
                    		<li>                       	
	                        	<div class="list-block"><div><span class="feature-img"><%= image_tag("smartphone.png", :alt => "") %></span><span>Wi-Fi</span></div></div>
	                        </li>
                    	<% end %>

                    	<% if @property.is_gym %>
                    		<li>                       	
	                        	<div class="list-block"><div><span class="feature-img"><%= image_tag("gym.png", :alt => "") %></span><span>Gym</span></div></div>
	                        </li>
                    	<% end %>

                    	<% if @property.is_pool %>
                    		<li>                       	
	                        	<div class="list-block"><div><span class="feature-img"><%= image_tag("swimming-pool.png", :alt => "") %></span><span>Pool/Hot Tub</span></div></div>
	                        </li>
                    	<% end %>              
                        
                        
                    </ul>
                </div>
                
                <div class="col-md-12 mb-4 pro-feature-sec">
                	<h5>Additional Features</h5>
                	<ul class="features-list">
                    	<% if @property.is_dogs %>
                    		<li>                       	
	                        	<div class="list-block"><div><span class="feature-img"><%= image_tag("pet.png", :alt => "") %></span><span>Dogs</span></div></div>
	                        </li>
                    	<% end %>

                    	<% if @property.is_cats %>
                    		<li>                       	
	                        	<div class="list-block"><div><span class="feature-img"><%= image_tag("cat.png", :alt => "") %></span><span>Cats</span></div></div>
	                        </li>
                    	<% end %>

                    	<% if @property.is_wheelchair %>
                    		<li>                       	
	                        	<div class="list-block"><div><span class="feature-img"><%= image_tag("wheelchair.png", :alt => "") %></span><span>Wheelchair Access</span></div></div>
	                        </li>
                    	<% end %>

                    	<% if @property.is_smoking %>
                    		<li>                       	
	                        	<div class="list-block"><div><span class="feature-img"><%= image_tag("smoke.png", :alt => "") %></span><span>Smoking</span></div></div>
	                        </li>
                    	<% end %>                 	
                        
                        
                    </ul>
                </div>
                
                
              </div>
              
              <div class="row l-p-loction-sec">
              	<div class="col-md-12"><hr></div>
              	<div class="col-md-6">
                	<h5>Location</h5>
                </div>
                <div class="col-md-6 text-right">
                	<span class="location-address"><%= @property.address %></span>
                </div>
                <div class="col-md-12 l-p-l-map">
                	<% if @property.address %>
                    <%= render 'map' %>
                  <% end %>				    
                </div>
              </div>
              </div>
           </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- landloard-profile end here -->

app/views/properties/update.html.erb
<h1>Properties#update</h1>
<p>Find me in app/views/properties/update.html.erb</p>