config/routes.rb
Rails.application.routes.draw do  
 
  
  
  
  ActiveAdmin.routes(self)
  get 'requests/index'
  get 'requests/show'
  get 'requests/update'
  get 'requests/destroy'
  get 'requests/edit'
  get 'requests/create'
  get 'requests/new'
  root 'pages#home'
  get 'pages/home'
  get 'pages/home_landlord'
  get 'properties/index'
  get 'properties/new'
  get 'properties/create'
  get 'properties/update'
  get 'properties/show'
  get 'properties/edit'
  get 'properties/destroy'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :properties
      devise_for :users, 
                  :controllers => {registrations: "api/v1/registrations", sessions: "api/v1/sessions"},
                  path_names: { sign_in: :login }
      resources :users, only: [:show]  
      resources :purchases, only: [:index]
      resources :points, only: [:index]          
    end
  end

  devise_for :users,
             :controllers => {registrations: 'registrations'},
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'}
             
  resources :landlords do
    member do
      delete :delete_image_attachment
    end  
  end  
  resources :tenants do
    member do
      delete :delete_image_attachment
    end  
  end  
  resources :properties
  resources :requests do
    member do
      get 'responses'
      get 'response_property'
      patch :activate
      put :activate
      get 'congratulations'
    end  
  end  
  resources :properties do
    member do
      get 'all_requests'
      get 'show_request'
      delete :delete_image_attachment
      patch :activate
      put :activate
      get 'congratulations'
    end  
  end

  resources :purchases
  resources :points

  resources :properties do
    resources :requests do        
      resources :purchases        
    end  
  end

  resources :properties do
    resources :requests do 
      resources :points         
    end  
  end

  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"

 

  get '/notifications' => 'notifications#index'

  get '/payment_method' => "landlords#payment"
  post '/add_card' => "landlords#add_card"

  resources :conversations, only: [:index, :create]  do
    resources :messages, only: [:index, :create]
  end

  require 'sidekiq/web'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'
end

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_footer.html.erb
<footer>
        <section class="footer-top">
          <div class="container">
            <div class="row">
              <div class="col-md-4">
              <div class="brand-logo"><a href="index.html"><%= image_tag("logo.png", :alt => "logo") %></a></div>
                <p>Homie makes finding a place to live quick and easy.</p>
              </div>
              <div class="col-md-3">
                <h5>Tenants</h5>
                <ul class="f-menu">
                  <!-- <li><a href="contact-us.html">How It Works</a></li>
                  <li><a href="#">Blog</a></li> -->
                  <li><a href="mailto: info@homie.com">Contact us</a></li>
                </ul>
              </div>
              <div class="col-md-3">
                <h5>Landlords</h5>
                <ul class="f-menu">
                  <!-- <li><a href="contact-us.html">Publish Your Property</a></li> -->
                  <li><a href="mailto: info@homie.com">Contact us</a></li>
                </ul>
              </div>
              <div class="col-md-2">
                <!-- <ul class="social-media">
                  <li class="social-media-1"><a href="#"><i class="fa fa-facebook-official"></i></a></li>
                  <li class="social-media-2"><a href="#"><i class="fa fa-instagram"></i></a></li>
                  <li class="social-media-3"><a href="#"><i class="fa fa-twitter"></i></a></li>
                  <li class="social-media-4"><a href="#"><i class="fa fa-youtube-play"></i></a></li>
                </ul> -->
              </div>
            </div>
          </div>
        </section>
        <div class="container">
        <section class="copyright-footer">
          
            <div class="row">
              <div class="col-md-5">
                <p>Copyright © 2019. Homie. All rights reserved</p>
              </div>
              <div class="col-md-7">
                <ul class="term-menu">
                  <li><a href="#">Terms</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                    <!-- <li><a href="#">Cookies</a></li>
                    <li><a href="#">Frequently asked Questions</a></li> -->
                    <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
                </ul>
              </div>
            </div>
        </section>
        </div>
      </footer>

app/views/shared/_header.html.erb
<header class="header landloard-profile-head border-bottom" style="margin-bottom: 30px;">
  <div class="container">
    <div class="row">
      <div class="col-sm-2 brand"> <a href="
        <% if current_user.role == 'landlord' %>
          <%= properties_path %>
        <% else %>
          <%= requests_path %>
        <% end %>
        "><%= image_tag("logo.png", :alt => "") %></a> </div>
        <div class="col-sm-10">
          <nav class="navbar">
            <div class="navbar-header"> 
              <a href="javascript:void()" class="menu-btn"><%= image_tag("menu-icon.png", :alt => "menu-icon") %> <%= image_tag("close-icon.png", :alt => "close-icon") %></a> 
            </div>
            <div id="bs-navbar">
              <ul class="nav navbar-nav">
                <li class="home-menu-m"><a href="
                <% if current_user.role == 'landlord' %>
                  <%= properties_path %>
                <% else %>
                  <%= requests_path %>
                <% end %>
                ">Home</a> 
                </li>
                <% if current_user.role == 'landlord' %>
                  <li class="active"><a href="<%= properties_new_path %>">+ New Property</a></li>
                <% else %>
                  <li class="active"><a href="<%= requests_new_path %>">+ New Request</a></li>
                <% end %>
                
                <li><a href="<%= conversations_path %>"><i class="fa fa-envelope-o"></i></a></li>
                <li>
              <%= link_to notifications_path do %>
                <i class="fa fa-bell-o icon-babu"></i>
                <span class="badge" id="navbar_num_of_unread"><%= current_user.unread if current_user.unread > 0 %></span>
              <% end %>
            </li>
              
              <li> 
                <% if profile(current_user) %>
                  <%= link_to current_user.email, profile(current_user), class: "user-email" %>
                <% else %>
                  <a href="<%= create_profile(current_user) %>" class="user-email"><%= current_user.email %></a>
                <% end %>
                
                 </li>
                <li style="vertical-align: middle;" class="" id="m-menu">
                  <div class="l-profile-img " >
                    <%= showavatarsmall(current_user) %>
                    <ul class=" chat-menu1">
                      <li><% if profile(current_user) %>
                  <%= link_to 'View Profile', profile(current_user) %>
                <% else %>
                  <a href="<%= create_profile(current_user) %>">View profile</a>
                <% end %></li>
                      <li><%= link_to destroy_user_session_path, method: :delete do %>
      Log out
      <% end %></li>
                    </ul>
                  </div>
                </li>
                
              </ul>
            </div>
          </nav>
        </div>
        
      </div>
    </div>
  </header>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% if key.include? "alert" %>
        <% key = "alert" %>
      <% elsif key.include? "error" %>
        <% key = "error" %>
      <% end %>
      <% type = key.to_s.gsub('alert','error').gsub('notice','success') %>
      toastr['<%= type %>']('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_notlogedheader.html.erb
<header class="header border-bottom" style="margin-bottom: 30px;">
          <div class="container">
            <div class="row">
              <div class="col-sm-2 brand"> <a href="/"><%= image_tag("logo.png", :alt => "logo") %></a> </div>
              <div class="col-sm-10">
                <nav class="navbar">
                  <div class="navbar-header"> <a href="javascript:void()" class="menu-btn"><%= image_tag("menu-icon.png", :alt => "menu-icon") %> <%= image_tag("close-icon.png", :alt => "close-icon") %></a> </div>
                  <div id="bs-navbar">
                    <ul class="nav navbar-nav">
                      <li class="active"><% if current_page?('http://localhost:3000/pages/home_landlord') %>
                        <a href="<%= root_path %>">Looking For a Place?</a>
                        <% else %>
                        <a href="<%= pages_home_landlord_path %>">Are You a Landlord?</a>
                      <% end %></li>
                      <li><a href="<%= new_user_session_path %>">Login</a></li>
                      <li><a href="<%= new_user_registration_path %>" class="primary-btn">Sign Up</a></li>
                    </ul>
                  </div>
                </nav>
              </div>
            </div>
          </div>
        </header>