config/routes.rb
Rails.application.routes.draw do  
 
  
  
  
  ActiveAdmin.routes(self)
  get 'requests/index'
  get 'requests/show'
  get 'requests/update'
  get 'requests/destroy'
  get 'requests/edit'
  get 'requests/create'
  get 'requests/new'
  root 'pages#home'
  get 'pages/home'
  get 'pages/home_landlord'
  get 'properties/index'
  get 'properties/new'
  get 'properties/create'
  get 'properties/update'
  get 'properties/show'
  get 'properties/edit'
  get 'properties/destroy'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :properties
      devise_for :users, 
                  :controllers => {registrations: "api/v1/registrations", sessions: "api/v1/sessions"},
                  path_names: { sign_in: :login }
      resources :users, only: [:show]  
      resources :purchases, only: [:index]
      resources :points, only: [:index]          
    end
  end

  devise_for :users,
             :controllers => {registrations: 'registrations'},
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'}
             
  resources :landlords do
    member do
      delete :delete_image_attachment
    end  
  end  
  resources :tenants do
    member do
      delete :delete_image_attachment
    end  
  end  
  resources :properties
  resources :requests do
    member do
      get 'responses'
      get 'response_property'
      patch :activate
      put :activate
      get 'congratulations'
    end  
  end  
  resources :properties do
    member do
      get 'all_requests'
      get 'show_request'
      delete :delete_image_attachment
      patch :activate
      put :activate
      get 'congratulations'
    end  
  end

  resources :purchases
  resources :points

  resources :properties do
    resources :requests do        
      resources :purchases        
    end  
  end

  resources :properties do
    resources :requests do 
      resources :points         
    end  
  end

  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"

 

  get '/notifications' => 'notifications#index'

  get '/payment_method' => "landlords#payment"
  post '/add_card' => "landlords#add_card"

  resources :conversations, only: [:index, :create]  do
    resources :messages, only: [:index, :create]
  end

  require 'sidekiq/web'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'
end

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/request.rb
class Request < ApplicationRecord
	validates :address, presence: true
	validates :home_type, presence: true
	validates :bed_room, presence: true
	validates :bath_room, presence: true
	validates :duration, presence: true
	validates :arrival_date, presence: true
	validates :min_budget, presence: true
	validates :max_budget, presence: true
	

	belongs_to :user
	has_many :purchases
	has_many :points
	has_many :connections
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  
  before_action :set_request, except: [:index, :new, :create, :step1, :step2, :step3, :step4, :step5, :step6, :steplast]
  before_action :authenticate_user!, except: [:new, :create, :step1, :step2, :step3, :step4, :step5, :step6, :steplast]

  def response_property
    @property = Property.find(params[:format])
  end
  
  def responses    
    @purchases = Purchase.where(request_id: params[:id])    
  end

  def activate
    if @request.active?
      @request.update_attribute(:active, false)
    else
      @request.update_attribute(:active, true)
    end
    redirect_to request.referer
  end

  def steplast
    if current_user.nil?
      session[:request] = params
     # Redirect the user to register/login
      redirect_to new_user_registration_path  
    else
      @request = current_user.requests.build(request_params)
      if @request.save
        redirect_to @request, notice: "Saved..."
      else
        flash[:alert] = "Something went wrong..."
        render :new
      end
    end    
  end

  def index
    @requests = current_user.requests
  end
    
  

  def show
    authorize! :read, @request
    
  end

  def update
    authorize! :update, @request
    if @request.update(request_params)
      RequestMailer.update_request_email(@request).deliver_later
      RequestMailer.update_request_admin_email(@request).deliver_later
      
      
      MatchingJob.perform_later @request
      flash[:notice] = "Saved..."

    else
      flash[:alert] = "Something went wrong..."
    end
    redirect_to @request
  end

  def destroy
    authorize! :destroy, @request
    @request = Request.find(params[:id])
      @request.destroy

      redirect_to requests_path
  end

  def edit
    authorize! :edit, @request
  end

  def create
    if current_user.nil?
      session[:request] = params
     # Redirect the user to register/login
      redirect_to new_user_registration_path  
    else
      @request = current_user.requests.build(request_params)
      if @request.save
        RequestMailer.new_request_email(@request).deliver_later
        RequestMailer.new_request_admin_email(@request).deliver_later
        MatchingJob.perform_later @request
        render :congratulations, notice: "Saved..."
      else
        flash[:alert] = "Something went wrong..."
        render :new
      end
    end    
  end

  def new
    if user_signed_in?
      @request = current_user.requests.build
    else
      @request = Request.new
    end    
  end

  def congratulations
    
  end

  

  private
  def request_params
      params.require(:request).permit(:min_budget, :max_budget, :home_type, :room_type, :accommodate, :bed_room, :bath_room, :is_air, :is_parking, :is_washer, :is_balcony, :is_fireplace, :is_internet, :is_gym, :is_pool, :is_dogs, :is_cats, :is_wheelchair, :is_smoking, :city, :duration, :arrival_date, :active, address: [])
  end

  def set_request
    @request = Request.find(params[:id])
  end

end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_request.html.erb
<div class="col-md-4">
  <div class="apartment-pro-bx  new-design list-common">
    <div class="apartment-header">
    <div class="apt-inr-head">
    <span class="property-price"> $<%= request.min_budget %>-<%= request.max_budget %> </span>
      <% if current_user.id == request.user_id %>
       	<a href="<%= request_path(request) %>">
          <h5><%= request.home_type %></h5>
        </a>
      <% else %>
        <a href="<%= property_request_path(@property, request) %>">
          <h5><%= request.home_type %></h5>
        </a>
      <% end %>
      <span class="location-name"><%= request.city %></span> 
      </div>
    </div>
    <div class="apartment-dtl-list">
      <ul class="pro-dtl-list">
        <li>
          <span class="f-icon"><%= image_tag 'calendar.png' %> <span><%= request.arrival_date %> </span></span>  <span class="duration"><span><%= request.duration %></span> Months</span>
        </li>
        <li>
          <span class="f-icon"><%= image_tag 'bed-icon.png' %> <span><%= request.bed_room %></span> </span>  <span class="duration"><%= 'bedroom'.pluralize(request.bed_room) %></span>
        </li>
        <li>
          <span class="f-icon"><%= image_tag 'bathtub-icon.png' %> <span><%= request.bath_room %></span></span> <span class="duration"><%= 'bathroom'.pluralize(request.bath_room) %></span>
        </li>
      </ul>
      <% @purchases = Purchase.where(request_id: request.id) %>
      <div class="pro-btn-sec m-r-accepted-btn"> 
        <a href="<%= responses_request_path(request) %>" class="light-blue-btn">Responses <span>(<%= @purchases.count %>)</span></a> 
        
          <%= link_to 'Edit', edit_request_path(request), class: "light-red-btn" %>
                
      </div>
    </div>
  </div>
</div>

app/views/requests/_sidebar.html.erb
<div class="l-sidebar aside-1">
  <div class="landloard-profile-inbox">
    <%= showavatar(current_user) %>   
  </div>
  
  <ul class="l-menu">
    
    
    <li class="<%= cp(requests_path) %>"><a href="<%= requests_path %>"><span class="l-p-icon"><%= image_tag "home-icon.png" %></span> Requests</a></li>
    <% if profile(current_user) %>
      <li class="<%= cp(tenant_path(profile(current_user))) %>"> <a href="<%= tenant_path(profile(current_user)) %>"><span class="l-p-icon"><%= image_tag "user.png" %></span> Profile</a></li>
    <% else %>
      <li class="<%= cp(create_profile(current_user)) %>"> <a href="<%= create_profile(current_user) %>"><span class="l-p-icon"><%= image_tag "user.png" %></span> Profile</a></li>
    <% end %>
    <li class="<%= cp(conversations_path) %>"><a href="<%= conversations_path %>"><span class="l-p-icon"><%= image_tag "mail-icon-grey.png" %></span> Messages</a></li>
    <li><a href="<%= edit_user_registration_path %>"><span class="l-p-icon"><%= image_tag 'padlock-grey.png' %></span>Security</a></li>
    <li class="logout-link">
      <%= link_to destroy_user_session_path, method: :delete do %>
      <span class="l-p-icon"><%= image_tag 'logout.png' %></span>Log out
      <% end %>
    </li>
  </ul>
  <div class="l-side-btn-sec"> <a href="<%= requests_new_path %>" class="light-blue-btn">+ New Request</a> </div>
</div>

app/views/requests/create.html.erb
<h1>Requests#create</h1>
<p>Find me in app/views/requests/create.html.erb</p>

app/views/requests/destroy.html.erb
<h1>Requests#destroy</h1>
<p>Find me in app/views/requests/destroy.html.erb</p>

app/views/requests/index.html.erb
<section class="landloard-content main-landloard-profile-sec">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <%= render "sidebar" %>
      </div>
      <div class="col-md-9">
        <div class="landloard-rt-sec new-rt-landloard-sec">
          <div class="row">
            <% if @requests.count > 0 %>
              <%= render @requests %>
            <% else %>
              <p>Please create your first request</p>
            <% end %> 
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- landloard-profile end here -->

app/views/requests/response_property.html.erb
<section class="landloard-content">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
         <!-- Sidebar here -->
          <%= render "sidebar" %>
        </div>
        <div class="col-md-9">        	
          <div class="landloard-rt-sec">
          	<div class="row">
              <div class="col-md-12">
                <div class="back-to-req-sec">
            	    <a href="<%= properties_path %>" class="back-to-request">
                	<span class="back-arrow"></span> <span>Back to Properties</span>
                  </a>	
                </div>
              </div>
            </div>
            <div class="row">            
            <div class="col-md-12">
            	<div class="pro-l-open-property">
                <div class="row">
                 	<div class="col-md-6">
                    <div id="sync1" class="owl-carousel">
                      <% @property.images.each do |image| %>
            				    <div class="item">
            				      <%= image_tag image %>
            				    </div>
            				  <% end %>                 
                    </div>
                    <div id="sync2" class="owl-carousel">
                      <% @property.images.each do |image| %>
            				    <div class="item">
            				      <%= image_tag image %>
            				    </div>
            				  <% end %>                  
                    </div>
                  </div>

              	  <div class="col-md-6">              	 	
                	 	<div class="row pro-l-head">
                      <div class="col-md-8">
                        <h4><%= @property.property_name %></h4>
                        <span class="location-address"><%= @property.address %></span>
                      </div>
                      <div class="col-md-4 property-price">
                        <h4>$<%= @property.price %></h4>
                      </div>
                    </div>
                    
                    <ul class="l-p-dtl-list">
                    	<li><span class="f-icon"><%= image_tag("real-estate.png", :alt => "") %></span> <%= @property.home_type %></li>
                      <li><span class="f-icon"><%= image_tag("shared.png", :alt => "") %></span> <%= @property.room_type %></li>
                    	<li><span class="f-icon"><%= image_tag("bed-grey-icon-1.png", :alt => "") %></span><span class="f-count"><%= @property.bed_room %></span> Bedrooms</li>
                      <li><span class="f-icon"><%= image_tag("accommodate.png", :alt => "") %></span><span class="f-count"><%= @property.accommodate %></span> Accommodate </li>
                      <li><span class="f-icon"><%= image_tag("bathtub-grey-icon-1.png", :alt => "") %></span><span class="f-count"><%= @property.bath_room %></span> Bathrooms</li>
                      <li><span class="f-icon"><%= image_tag("calendar.png", :alt => "") %></span><span class="f-count"><%= @property.minimum_lease %></span></li>
                    </ul>                    
                  </div>

                  <div class="col-md-12">
                 	  <div class="p-l-desc">
                 	    <p><%= @property.summary %></p>
                    </div>
                  </div>
                </div>
                            
                <div class="row">
              	  <div class="col-md-12 mt-4 mb-4 pro-feature-sec">
                	  <h5>Features</h5>
                	  <ul class="features-list">
                    	<% if @property.is_air %>
                    		<li>                       	
	                        <div class="list-block"><div><span class="feature-img"><%= image_tag("air-conditioner.png", :alt => "") %></span><span>Airconditioning </span></div></div>
	                      </li>                    		
                    	<% end %>
                    	<% if @property.is_parking %>
                    		<li>                       	
	                        <div class="list-block"><div><span class="feature-img"><%= image_tag("parking.png", :alt => "") %></span><span>Parking/
								          Garage </span></div></div>
	                      </li>                    		
                    	<% end %>

                    	<% if @property.is_washer %>
                    		<li>                       	
	                        <div class="list-block"><div><span class="feature-img"><%= image_tag("washing-machine.png", :alt => "") %></span><span>Washing machine </span></div></div>
	                      </li>
                    	<% end %>

                    	<% if @property.is_balcony %>
                    		<li>                       	
	                        <div class="list-block"><div><span class="feature-img"><%= image_tag("balcony.png", :alt => "") %></span><span>Balcony</span></div></div>
	                      </li>
                    	<% end %>

                    	<% if @property.is_fireplace %>
                    		<li>                       	
	                        <div class="list-block"><div><span class="feature-img"><%= image_tag("fireplace.png", :alt => "") %></span><span>Fireplace</span></div></div>
	                      </li>
                    	<% end %>

                    	<% if @property.is_internet %>
                    		<li>                       	
	                        <div class="list-block"><div><span class="feature-img"><%= image_tag("smartphone.png", :alt => "") %></span><span>Wi-Fi</span></div></div>
	                      </li>
                    	<% end %>

                    	<% if @property.is_gym %>
                    		<li>                       	
	                        <div class="list-block"><div><span class="feature-img"><%= image_tag("gym.png", :alt => "") %></span><span>Gym</span></div></div>
	                      </li>
                    	<% end %>

                    	<% if @property.is_pool %>
                    		<li>                       	
	                        <div class="list-block"><div><span class="feature-img"><%= image_tag("swimming-pool.png", :alt => "") %></span><span>Pool/Hot Tub</span></div></div>
	                       </li>
                    	<% end %>
                        
                    </ul>
                  </div>

                  <div class="col-md-12 mb-4 pro-feature-sec">
                	  <h5>Additional Features</h5>
                	  <ul class="features-list">
                    	<% if @property.is_dogs %>
                    		<li>                       	
	                        <div class="list-block"><div><span class="feature-img"><%= image_tag("pet.png", :alt => "") %></span><span>Dogs</span></div></div>
	                      </li>
                    	<% end %>

                    	<% if @property.is_cats %>
                    		<li>                       	
	                        <div class="list-block"><div><span class="feature-img"><%= image_tag("cat.png", :alt => "") %></span><span>Cats</span></div></div>
	                      </li>
                    	<% end %>

                    	<% if @property.is_wheelchair %>
                    		<li>                       	
	                        <div class="list-block"><div><span class="feature-img"><%= image_tag("wheelchair.png", :alt => "") %></span><span>Wheelchair Access</span></div></div>
	                      </li>
                    	<% end %>

                    	<% if @property.is_smoking %>
                    		<li>                       	
	                        <div class="list-block"><div><span class="feature-img"><%= image_tag("smoke.png", :alt => "") %></span><span>Smoking</span></div></div>
	                      </li>
                    	<% end %> 
                        
                    </ul>
                  </div>
                </div>
              
                <div class="row l-p-loction-sec">
              	  <div class="col-md-12"><hr></div>
              	  <div class="col-md-6">
                	  <h5>Location</h5>
                  </div>
                  <div class="col-md-6 text-right">
                	  <span class="location-address"><%= @property.address %></span>
                  </div>
                  <div class="col-md-12 l-p-l-map">
                	  <% if @property.address %>
                      <%= render 'properties/map' %>
                    <% end %>				    
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="card landloard-rt-sec">
          <div class="row">
            <div class="col-md-12">
              <div class="divider-h"></div>
              <div class="media l-media-object"> 
                <% if profile(@property.user).avatar.attached? %>
                  <%= image_tag profile(@property.user).avatar, size: "75x75" , class: "mr-3  rounded-circle" %>
                <% end %>

                <div class="media-body">
                  <h4><%= profile(@property.user).first_name %> <%= profile(@property.user).last_name %></h4>
                  <span class="postion-text">Tenant</span>
                </div>
                <div class="chat-footer l-open-pro-footer">
                  
                  <%= link_to "Message " + profile(@property.user).first_name, conversations_path(sender_id: @property.user_id, recepient_id: current_user.id), method: :post, class: "primary-btn" %>
                </div>
              </div>
              <p class="mb-4"><%= profile(@property.user).information %></p>                        
              
            </div>
          </div>
        </div>        
      </div>

      
      </div>
    </div>
  </section>
  <!-- landloard-profile end here -->

app/views/requests/responses.html.erb
<section class="landloard-content">
  		<div class="container">
        	<div class="row">
        	<div class="col-md-3">
            	<!-- Sidebar here -->
          		<%= render "sidebar" %>
            </div>
            
            <div class="col-md-9">
            	<div class="landloard-rt-sec">
                	<div class="row">
                    	<% @purchases.each do |purchase| %>
                    	<%	@property = Property.find( purchase.property_id) %>
                    		<div class="col-md-4">
	                        	<div class="property-slide-bx">
	                            	<div class="property-slider-01 owl-carousel owl-theme">
		                                <% @property.images.each do |image| %>
		                                	<div class="item">
				                            	<div class="propert-image-box">
				                            		<%= image_tag image %>
				                            	</div>
			                                </div>
		                                <% end %>	                                
	                                </div>
	                                <div class="property-detail-bx" style="display: flex;">
	                                	<div class="pro-dtl-sec">
	                                    	<%= link_to response_property_request_url(@request, @property) do %>
	                                    		<h5><%= @property.property_name %></h5>
	                                    	<% end %>
	                                        <span class="city-name"><%= @property.address %></span>
	                                    </div>
	                                    <div class="pro-bed-bx">
	                                    	<ul>
	                                        	<li><span class="bed-icon"><%= image_tag("bed-icon.png", :alt => "") %></span> <span class="pro-count"><%= @property.bed_room %></span></li>
	                                            <li><span class="bathtub-icon"><%= image_tag("bathtub-icon.png", :alt => "") %></span> <span class="pro-count"><%= @property.bath_room %></span></li>
	                                        </ul>
	                                    </div>
	                                </div>	                                
	                        	</div>	                        	
	                        </div>
                    	<% end %> 
                    </div>
                </div>
            </div>
            </div>
        </div>	
  </section>
  <!-- landloard-profile end here -->

app/views/requests/show.html.erb
<section class="landloard-content main-landloard-profile-sec">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <%= render 'sidebar' %>
      </div>
      <div class="col-md-9">
  	
        <div class="landloard-rt-sec">
       		<div class="row">
           	<div class="col-md-12">
             	<div class="back-to-req-sec">
              	<a href="<%= requests_path %>" class="back-to-request">
                	<span class="back-arrow"></span> <span>Back to requests</span>
                </a>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
            	<div class="pro-l-open-property">
                <div class="row pro-l-head">
                  <div class="col-md-3 pr-0"> <%= image_tag "apartment-big-icon.png" %> </div>
                  <div class="col-md-6">
                    <h4><%= @request.home_type %></h4>
                    <span class="location-address"><%= @request.city %> 
                      <% @districts = @request.address.gsub(/(\[\"|\"\])/, '').split('", "') %>                      
                      (<%= @districts.map{|district| district}.join(", ") %>)
                      
                    </span>
                    <ul class="pro-dtl-list">
                      <li><span class="f-icon"><%= image_tag("real-estate.png", :alt => "") %></span> <%= @request.home_type %></li>
                      
                      <li><span class="f-icon"><%= image_tag "calendar.png" %></span> <span><%= @request.arrival_date %> - <%= @request.duration %></span> Months</li>
                      <li><span class="f-icon"><%= image_tag "bed-grey-icon-1.png" %></span> <span><%= @request.bed_room %></span> <%= 'bedroom'.pluralize(@request.bed_room) %></li>
                      <li><span class="f-icon"><%= image_tag "bathtub-grey-icon-1.png" %></span> <span><%= @request.bath_room %></span> <%= 'bathroom'.pluralize(@request.bath_room) %></li>

                    </ul>
                  </div>
                  <div class="col-md-3 text-right">
                	 <div class="budget ">Budget:</div>
                	 <h4>$<%= @request.min_budget %>-<%= @request.max_budget %></h4>
                    <div class="rt-t-edit-sec">
                      <a href="<%= edit_request_path %>" class="light-blue-btn"><i class="fa fa-pencil"></i> Edit Request</a>
                      <% if @request.active? %>
                        <%= link_to 'Deactivate', activate_request_path(@request),       method: :put, data: { confirm: 'This request would be deactivated' }, class: "light-red-btn" %>
                      <% else %>
                        <%= link_to 'Activate', activate_request_path(@request), method: :put, data: { confirm: 'This request would be activated' }, class: "light-red-btn" %>
                      <% end %>
                    </div>
                   </div>
                  <div class="col-md-12">
               		 <hr>
                  </div>
                
                 
                
              </div>
                
              
              <div class="row">
              	<div class="col-md-12 mt-0 mb-2 pro-feature-sec">
                	<h5>Features</h5>
                	<ul class="features-list">
                    	<% if @request.is_air %>
                        <li>                        
                            <div class="list-block"><div><span class="feature-img"><%= image_tag("air-conditioner.png", :alt => "") %></span><span>Airconditioning </span></div></div>
                          </li>                       
                      <% end %>

                      <% if @request.is_parking %>
                        <li>                        
                            <div class="list-block"><div><span class="feature-img"><%= image_tag("parking.png", :alt => "") %></span><span>Parking/
                Garage </span></div></div>
                          </li>                       
                      <% end %>

                      <% if @request.is_washer %>
                        <li>                        
                            <div class="list-block"><div><span class="feature-img"><%= image_tag("washing-machine.png", :alt => "") %></span><span>Washing machine </span></div></div>
                          </li>
                      <% end %>

                      <% if @request.is_balcony %>
                        <li>                        
                            <div class="list-block"><div><span class="feature-img"><%= image_tag("balcony.png", :alt => "") %></span><span>Balcony</span></div></div>
                          </li>
                      <% end %>

                      <% if @request.is_fireplace %>
                        <li>                        
                            <div class="list-block"><div><span class="feature-img"><%= image_tag("fireplace.png", :alt => "") %></span><span>Fireplace</span></div></div>
                          </li>
                      <% end %>

                      <% if @request.is_internet %>
                        <li>                        
                            <div class="list-block"><div><span class="feature-img"><%= image_tag("smartphone.png", :alt => "") %></span><span>Wi-Fi</span></div></div>
                          </li>
                      <% end %>

                      <% if @request.is_gym %>
                        <li>                        
                            <div class="list-block"><div><span class="feature-img"><%= image_tag("gym.png", :alt => "") %></span><span>Gym</span></div></div>
                          </li>
                      <% end %>

                      <% if @request.is_pool %>
                        <li>                        
                            <div class="list-block"><div><span class="feature-img"><%= image_tag("swimming-pool.png", :alt => "") %></span><span>Pool/Hot Tub</span></div></div>
                          </li>
                      <% end %>                    
                        
                    </ul>
                </div>
                
                <div class="col-md-12 mb-4 pro-feature-sec">
                	<h5>Additional Features</h5>
                	<ul class="features-list">
                    	<% if @request.is_dogs %>
                        <li>                        
                            <div class="list-block"><div><span class="feature-img"><%= image_tag("pet.png", :alt => "") %></span><span>Dogs</span></div></div>
                          </li>
                      <% end %>

                      <% if @request.is_cats %>
                        <li>                        
                            <div class="list-block"><div><span class="feature-img"><%= image_tag("cat.png", :alt => "") %></span><span>Cats</span></div></div>
                          </li>
                      <% end %>

                      <% if @request.is_wheelchair %>
                        <li>                        
                            <div class="list-block"><div><span class="feature-img"><%= image_tag("wheelchair.png", :alt => "") %></span><span>Wheelchair Access</span></div></div>
                          </li>
                      <% end %>

                      <% if @request.is_smoking %>
                        <li>                        
                            <div class="list-block"><div><span class="feature-img"><%= image_tag("smoke.png", :alt => "") %></span><span>Smoking</span></div></div>
                          </li>
                      <% end %>                          
                    </ul>
                </div>
                
                
              </div>
              
              
              </div>
           </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- landloard-profile end here -->

app/views/requests/update.html.erb
Update