config/routes.rb
Rails.application.routes.draw do  
 
  
  
  
  ActiveAdmin.routes(self)
  get 'requests/index'
  get 'requests/show'
  get 'requests/update'
  get 'requests/destroy'
  get 'requests/edit'
  get 'requests/create'
  get 'requests/new'
  root 'pages#home'
  get 'pages/home'
  get 'pages/home_landlord'
  get 'properties/index'
  get 'properties/new'
  get 'properties/create'
  get 'properties/update'
  get 'properties/show'
  get 'properties/edit'
  get 'properties/destroy'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :properties
      devise_for :users, 
                  :controllers => {registrations: "api/v1/registrations", sessions: "api/v1/sessions"},
                  path_names: { sign_in: :login }
      resources :users, only: [:show]  
      resources :purchases, only: [:index]
      resources :points, only: [:index]          
    end
  end

  devise_for :users,
             :controllers => {registrations: 'registrations'},
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'}
             
  resources :landlords do
    member do
      delete :delete_image_attachment
    end  
  end  
  resources :tenants do
    member do
      delete :delete_image_attachment
    end  
  end  
  resources :properties
  resources :requests do
    member do
      get 'responses'
      get 'response_property'
      patch :activate
      put :activate
      get 'congratulations'
    end  
  end  
  resources :properties do
    member do
      get 'all_requests'
      get 'show_request'
      delete :delete_image_attachment
      patch :activate
      put :activate
      get 'congratulations'
    end  
  end

  resources :purchases
  resources :points

  resources :properties do
    resources :requests do        
      resources :purchases        
    end  
  end

  resources :properties do
    resources :requests do 
      resources :points         
    end  
  end

  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"

 

  get '/notifications' => 'notifications#index'

  get '/payment_method' => "landlords#payment"
  post '/add_card' => "landlords#add_card"

  resources :conversations, only: [:index, :create]  do
    resources :messages, only: [:index, :create]
  end

  require 'sidekiq/web'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'
end

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/landlord.rb
class Landlord < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :information, presence: true

  belongs_to :user
  has_one_attached :avatar
end

app/controllers/landlords_controller.rb
class LandlordsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_landlord, except: [:index, :new, :create, :payment, :add_card]
  
  def new 
     if current_user.landlord
       redirect_to current_user.landlord, notice: "You already have profile."
     else
       if current_user.role == 'tenant'
         redirect_to current_user.tenant, notice: "You are tenant! You couldn't create landlord profile!"
       else
         @landlord = Landlord.new(user_id: current_user.id)
       end
     end  
  end

  def create
    @landlord = Landlord.new(landlord_params)
    @landlord.user_id = current_user.id
    if @landlord.save
      redirect_to @landlord, notice: "Data saved"
    else
      if @landlord.errors.full_messages.present?
        if @landlord.errors.full_messages.each_with_index do |msg,i|
          flash["alert"+i.to_s] = msg
        end
        end
      end
      render :new
    end  
  end

  def update
    authorize! :update, @landlord
    if @landlord.update(landlord_params)
      redirect_to @landlord, notice: "Data saved"
    else
      if @landlord.errors.full_messages.present?
        if @landlord.errors.full_messages.each_with_index do |msg,i|
          flash["alert"+i.to_s] = msg
        end
        end
      end
      # flash[:alert] = "Something went wrong..."
      render 'edit'
    end
    
  end

  def edit
    authorize! :edit, @landlord
  end

  def destroy
    authorize! :destroy, @landlord
  end

  def index
  end

  def show
    @properties = current_user.properties
    authorize! :read, @landlord
  end

  def payment
    session["HTTP_REFERER"] = request.headers["HTTP_REFERER"]
  end

  def add_card
    updated = false
    if current_user.stripe_id.blank?
      customer = Stripe::Customer.create(
        email: current_user.email
      )
      current_user.stripe_id = customer.id
      current_user.save

      # Add Credit Card to Stripe
      customer.sources.create(source: params[:stripeToken])
    else
      customer = Stripe::Customer.retrieve(current_user.stripe_id)
      customer.source = params[:stripeToken]
      customer.save
      updated = true
    end

    if updated == true
      flash[:notice] = "Your card is updated."
    else
      flash[:notice] = "Your card is saved."
    end    
    if session["HTTP_REFERER"].present?
      if session["HTTP_REFERER"].include? "/landlords/new"
        redirect_to new_landlord_path
      elsif session["HTTP_REFERER"].include? "/payment_method"
        redirect_to payment_method_path
      elsif session["HTTP_REFERER"].include? "/show_request"
        if session["property_id"].present?
          redirect_to all_requests_property_path(session["property_id"])
        else
          redirect_to root_path
        end
      else
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to payment_method_path
  end

  def delete_image_attachment
    @image = ActiveStorage::Attachment.find(params[:id])
    @image.purge
    redirect_back(fallback_location: request.referer, notice: "Saved...")
  end

  private 
  def set_landlord
      @landlord = Landlord.find(params[:id])
    end
  def landlord_params
      params.require(:landlord).permit(:first_name, :last_name, :information, :phone_number, :address, :avatar)
  end
end

app/helpers/landlords_helper.rb
module LandlordsHelper
end

app/views/landlords/_sidebar.html.erb
<div class="l-sidebar aside-1">
  <div class="landloard-profile-inbox">
    <% if @landlord %>
      <%= showavatar(@landlord.user) %>
    <% else %>
      <%= showavatar(current_user) %>
    <% end %>

    
  </div>
  <ul class="l-menu">
              
    <li class="<%= cp(properties_path) %>"> <a href="<%= properties_path %>"><span class="l-p-icon"><%= image_tag 'home-icon.png' %></span> Properties</a></li>
    <% if profile(current_user) %>
      <li class="<%= cp(landlord_path(profile(current_user))) %>"> 
        <a href="<%= landlord_path(profile(current_user)) %>"><span class="l-p-icon">                
          <%= image_tag 'user.png' %>                
        </span>Profile</a>
      </li>
    <% else %>
      <li class="<%= cp(create_profile(current_user)) %>"> 
        <a href="<%= create_profile(current_user) %>"><span class="l-p-icon">                
          <%= image_tag 'user.png' %>                
        </span>Profile</a>
      </li>
    <% end %>
    <li class="<%= cp(conversations_path) %>"><a href="<%= conversations_path %>"><span class="l-p-icon"><%= image_tag "mail-icon-grey.png" %></span> Messages</a></li>
    <li class="<%= cp(edit_user_registration_path) %>"><a href="<%= edit_user_registration_path %>"><span class="l-p-icon"><%= image_tag 'padlock-grey.png' %></span>Security</a></li>
    <% if current_user.stripe_id  %>
      <li class="<%= cp(payment_method_path) %>"><a href="<%= payment_method_path %>"><span class="l-p-icon"><%= image_tag 'credit-card.png' %></span>Update Credit Card</a></li>
    <% else %>
      <li class="<%= cp(payment_method_path) %>"><a href="<%= payment_method_path %>"><span class="l-p-icon"><%= image_tag 'credit-card.png' %></span> Add Credit Card</a></li>
    <% end %>
              
              
    <li class="logout-link">
      <%= link_to destroy_user_session_path, method: :delete do %>
        <span class="l-p-icon"><%= image_tag 'logout.png' %></span>Log out
      <% end %>
    </li>
  </ul>
  <div class="l-side-btn-sec"> <a href="#" class="light-blue-btn">+ New Property</a> </div>
</div>

app/views/landlords/create.html.erb
<h1>Landlords#create</h1>
<p>Find me in app/views/landlords/create.html.erb</p>

app/views/landlords/destroy.html.erb
<h1>Landlords#destroy</h1>
<p>Find me in app/views/landlords/destroy.html.erb</p>

app/views/landlords/edit.html.erb
<section class="landloard-content main-landloard-profile-sec">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <%= render 'sidebar' %>
        </div>
        <div class="col-md-9">
          <%= form_for @landlord do |f| %>
          <div class="landloard-rt-sec">
            <div class="row">
              <div class="col-md-12">
                <div class="media pb-4"> 
                  <% if @landlord.avatar.attached? %>
                  <%= image_tag @landlord.avatar, size: "122x122", class: "mr-3 mt-3 rounded-circle" %>
                  <% end %> 
                  <div class="media-body">
                    <p>Clear frontal face photos are an important way for tenants to learn about each other.  Be sure to use a photo that clearly shows your face and doesn’t include any personal or sensitive info you’d rather not have tenants see.</p>
                    <div class="landloard-profile-btn-sec"> <%= f.file_field :avatar, direct_upload: true, class: "blue-outline-btn arrow-none-btn" %> 
                      <% if @landlord.avatar.attached? %>
                        <a href="<%= delete_image_attachment_landlord_path(@landlord.avatar.id) %>" data-method="delete" class="light-red-btn">Delete</a>
                      <% end %>
                       </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="edit-landloard-profile">
                  <div class="form-group"> <i class="fa fa-user-o input-user-icon"></i>
                    <%= f.text_field :first_name, class: "form-control", placeholder: "First name" %>                    
                  </div>
                  <div class="form-group"> <i class="fa fa-user-o input-user-icon"></i>
                    <%= f.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
                  </div>                  
                  <div class="form-group">
                    <label>Add some information about you</label>
                    <%= f.text_area :information, class: "form-control", placeholder: "Information..." %>
                  </div>
                  <div class="form-group">
                    <label>Add your address</label>
                    <%= f.text_field :address, class: "form-control tenant-address" %> 
                  </div>
                  
                  
                  <div class="form-group">
                    <%= f.submit "Save", class: "primary-btn" %>                    
                  </div>
                </div>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </section>
  <!-- landloard-profile end here -->

app/views/landlords/index.html.erb
<h1>Landlords#index</h1>
<p>Find me in app/views/landlords/index.html.erb</p>

app/views/landlords/new.html.erb
<section class="landloard-content main-landloard-profile-sec">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <%= render 'sidebar' %>
        </div>
        <div class="col-md-9">
          <%= form_for @landlord do |f| %>
          <div class="landloard-rt-sec">
            <div class="row">
              <div class="col-md-12">
                <div class="media pb-4"> 
                  <% if @landlord.avatar.attached? %>
                    <%= image_tag @landlord.avatar, size: "122x122", class: "mr-3 mt-3 rounded-circle" %>
                  <% end %>
                  
                  <div class="media-body">
                    <p>Clear frontal face photos are an important way for tenants to learn about each other.  Be sure to use a photo that clearly shows your face and doesn’t include any personal or sensitive info you’d rather not have tenants see.</p>
                    <div class="landloard-profile-btn-sec"> <%= f.file_field :avatar, direct_upload: true, class: "blue-outline-btn arrow-none-btn" %> <% if @landlord.avatar.attached? %>
                        <a href="<%= delete_image_attachment_landlord_path(@landlord.avatar.id) %>" data-method="delete" class="light-red-btn">Delete</a>
                      <% end %> </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="edit-landloard-profile">
                  <div class="form-group"> <i class="fa fa-user-o input-user-icon"></i>
                    <%= f.text_field :first_name, class: "form-control", placeholder: "First name" %>                    
                  </div>
                  <div class="form-group"> <i class="fa fa-user-o input-user-icon"></i>
                    <%= f.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
                  </div>                  
                  <div class="form-group">
                    <label>Add some information about you</label>
                    <%= f.text_area :information, class: "form-control", placeholder: "Information..." %>
                  </div>
                  <div class="form-group">
                    <label>Add your address</label>
                    <%= f.text_field :address, class: "form-control" %> 
                  </div>
                  
                  
                  <div class="form-group">
                    <%= f.submit "Save", class: "primary-btn" %>                    
                  </div>
                </div>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </section>
  <!-- landloard-profile end here -->

app/views/landlords/payment.html.erb
<section class="landloard-content main-landloard-profile-sec">
  <div class="container" style="margin-top: 50px; margin-bottom: 50px;">
    

    <div class="row">
      <div class="col-md-3">
        <%= render 'landlords/sidebar' %>
      </div>

      <div class="col-md-9">
        
          
          
            <div class="container">
            <div class="payment-card-dt">
            <div class="panel-heading">Payment Method</div>
                <%= form_tag("/add_card", method: "post", id: "add-card") do %>
                  <label>
                    <span>Name on Card <span class="red-color">*</span></span>
                    <input name="cardholder-name" class="field" placeholder="Jane Doe" />
                  </label>

                  <label>
                    <span>Card Number <span class="red-color">*</span></span>
                    <div id="card-element" class="field"></div>
                  </label>

                  <div class="outcome">
                    <div class="error" role="alert"></div>
                  </div>

                  <% if current_user.stripe_id %>
                    <button type="submit" class="btn btn-normal btn-block">Update Card</button>
                  <% else %>
                    <button type="submit" class="btn btn-normal btn-block">Add Card</button>
                  <% end %>
                <% end %>
            </div>
          </div>
        </div>
     
    </div>
  </div>
</section>

<script src="https://js.stripe.com/v3/"></script>
<script>
  $(function() {

    var stripe = Stripe('<%= Rails.configuration.stripe[:publishable_key] %>');
    var elements = stripe.elements();

    var card = elements.create('card', {
      hidePostalCode: true,
      style: {
        base: {
          iconColor: '#F99A52',
          color: '#32315E',
          lineHeight: '48px',
          fontWeight: 400,
          fontFamily: '"Helvetica Neue", "Helvetica", sans-serif',
          fontSize: '15px',

          '::placeholder': {
            color: '#CFD7DF',
          }
        },
      }
    });

    card.mount('#card-element');

    function setOutcome(result) {

      var errorElement = document.querySelector('.error');
      errorElement.classList.remove('visible');

      if (result.token) {
        var form = $('#add-card');
        form.append($('<input type="hidden" name="stripeToken">').val(result.token.id));
        form.get(0).submit();
      } else if (result.error) {
        errorElement.textContent = result.error.message;
        errorElement.classList.add('visible');
      }
    }

    card.on('change', function(event) {
      setOutcome(event);
    });

    $('#add-card').on('submit', function(e) {
      e.preventDefault();
      var extraDetails = {
        name: $('input[name=cardholder-name]').value
      };
      stripe.createToken(card, extraDetails).then(setOutcome);
    });

  });
</script>

app/views/landlords/show.html.erb
<section class="landloard-content main-landloard-profile-sec">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <%= render 'sidebar' %>
        </div>

        <div class="col-md-9">        	
          
          <div class="landloard-rt-sec l-pro-head-bg">          		
            <div class="row">            

            <div class="col-md-12">
            	<div class="l-a-landloard-header">
                <div class="row">
                <div class="col-md-8">
            	<h2 class="heading-level-02">Hi, I’m <%= @landlord.first_name %> <%= @landlord.last_name %></h2>
                <ul class="profile-list">
                <li>  <p class="lives-in-paris-france">Lives in 
                <% if @landlord.address %>
                  <%= @landlord.address %>
                <% end %>
                        </p></li>
                	<li>Joined in <%= @landlord.created_at.strftime("%Y") %></li>
                    <!--<li><span><%= @properties.count %></span> available <%= pluralize_without_count(@properties.count, 'property') %> <a href="<%= properties_path %>">View all</a></li>-->
                </ul>
              
                </div>
                <div class="col-md-4 text-right">
                <a href="<%= properties_path %>" class="light-blue-btn req-btn">Properties <span class="count">(<%= @properties.count %>)</span></a>
                	<% if @landlord.user_id == current_user.id %>

                       <a class="light-red-btn req-red-btn" href="<%= edit_landlord_path %>"><i class="fa fa-pencil"></i></a> 
                    <% end %>

                    
                </div>
                </div>
                </div>
                <div class="l-a-landloard-header">
                	<h5><%= @landlord.first_name %> <%= @landlord.last_name %></h5>
                    <p><%= @landlord.information %></p>
                </div>                
               </div>
             </div>
            
      </div>
    </div>
  </section>
  <!-- landloard-profile end here -->
<div class="container">
	
	<% if current_user && current_user != @landlord.user %>
        <%= link_to "Send Message", conversations_path(sender_id: current_user.id, recepient_id: @landlord.user.id), method: :post, class: "btn btn-default" %>
    <% end %>
</div>

app/views/landlords/update.html.erb
<h1>Landlords#update</h1>
<p>Find me in app/views/landlords/update.html.erb</p>